### PR TITLE
Fix primary image

### PR DESCRIPTION
**Pull request by amit-choudhary**

### CODE REVIEW

**Comment by amit-choudhary** [comment]
@akshaysmurthy Please review.

**Comment by akshaysmurthy** [comment]
@amit-choudhary Unit tests aren't passing. It appears that they weren't passing since `29c3081d4ea3f4a2d0317e3fd6b7ca0e86ec455b`

**Comment by amit-choudhary** [comment]
@akshaysmurthy Fixed and pushed. Should we integrate CircleCI or Travis too?

**Comment by akshaysmurthy** [comment]
@amit-choudhary We should! A task for later I think.

**Pull request merged**
